### ISSUE TITLE
500 on /login

### ISSUE THREAD

**Issue by bendem** [jkcclemens/paste#113]
So I was trying to go to /login, but then the server was all like nah, bb, 500!
Right after verifying my email

**Comment by Zarthus** [comment]
try again i just fixed it using my wizard powers

**Comment by jkcclemens** [comment]
The first login after restarting the backend always 500s, and I still don't know why.

**Comment by bendem** [comment]
Much better
 
Tue Jan 22 18:11:08 GMT+01:00 2019 bendem <notifications@github.com>:
 
So I was trying to go to /login, but then the server was all like nah, bb, 500!
 Right after verifying my email

**Comment by jkcclemens** [comment]
I can't reproduce this locally and I can no longer reproduce this on paste.gg. Has anyone encountered it recently?
